using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
// Legacy Excel persistence removed; procedures are stored in SQLite.

namespace Rotronic
{
    //TODO : save step to db instead of excel, pre-define most calibration workflows to prevent user error.
    public partial class StepEditor : Form
    {
        private const string NewProcedureName = "New Procedure";
        // Pseudocode / Plan (detailed):
        // 1. Add a private boolean field `_hasUnsavedChanges` to track edits. (already present)
        // 2. Detect and prevent entry into accuracy cells when the corresponding
        //    "pass/fail" checkbox column is unchecked.
        //    - Define canonical column detection for:
        //        temp pass/fail -> "temppassfail"
        //        temperature accuracy -> columns containing both "accuracy" and "temp" / "temperature"
        //        hum pass/fail -> "humppassfail" / "humpassfail"
        //        humidity accuracy -> columns containing both "accuracy" and "hum" / "humidity"
        //      (All checks should be case-insensitive; missing columns are handled gracefully.)
        // 3. Wire `CellValidating` to prevent input into accuracy columns when the pass/fail box is unchecked.
        //    - On validating: if editing an accuracy cell and the related pass/fail is false, clear the cell value.
        // 4. When a pass/fail checkbox cell changes (CellValueChanged), if it becomes unchecked,
        //    clear any existing values in the corresponding accuracy cells for that row.
        // 5. Keep marking `_hasUnsavedChanges = true` on mutations (already done in existing handlers).
        // 6. Implement small helper methods:
        //    - `FindColumnIndexByName(string)` - finds column index by name/header case-insensitive.
        //    - `FindTemperatureAccuracyColumnIndex()` / `FindHumidityAccuracyColumnIndex()` - best-effort detection.
        //    - `GetCellBoolValue(rowIndex, colIndex)` - robustly interprets cell value as bool.
        //    - `ClearTempFields(rowIndex)` / `ClearHumFields(rowIndex)` - set accuracy cells to empty.
        // 7. Ensure all operations are safe if columns are absent or rows are out of range.
        // 8. Keep UI unobtrusive: do not show message boxes for each auto-clear, just enforce the rule.
        //
        // This comment block serves as the step-by-step plan. The code below implements it.

        private bool _hasUnsavedChanges = false;

        public StepEditor()
        {
            InitializeComponent();

            this.Load += StepEditor_Load;
            this.KeyPreview = true;
            this.KeyDown += StepEditor_KeyDown;

            // Wire FormClosing to check for unsaved changes
            this.FormClosing += StepEditor_FormClosing;


            // Wire DataGridView events to detect user edits
            // These assume `dataGridViewStep` exists (generated by the designer)
            dataGridViewStep.CellValueChanged += DataGridViewStep_Changed;
            dataGridViewStep.UserAddedRow += DataGridViewStep_Changed;
            dataGridViewStep.UserDeletedRow += DataGridViewStep_Changed;
            dataGridViewStep.RowsRemoved += DataGridViewStep_Changed;
            dataGridViewStep.CurrentCellDirtyStateChanged += DataGridViewStep_CurrentCellDirtyStateChanged;

            // New: validate cell entries to prevent invalid data entry for accuracy fields
            dataGridViewStep.CellValidating += DataGridViewStep_CellValidating;

            // New: enforce row behavior when Step is "Adjust"
            dataGridViewStep.CellBeginEdit += DataGridViewStep_CellBeginEdit;
            dataGridViewStep.CellFormatting += DataGridViewStep_CellFormatting;

            dataGridViewStep.CellContentClick += DataGridViewStep_CellContentClick;

            try
            {
                dataGridViewStep.DataBindingComplete -= DataGridViewStep_DataBindingComplete;
                dataGridViewStep.DataBindingComplete += DataGridViewStep_DataBindingComplete;
            }
            catch { }

            try
            {
                ApplyTwoDecimalFormatting(dataGridViewStep);
            }
            catch { }

            comboBoxStepList.SelectedIndexChanged += comboBoxStepList_SelectedIndexChanged;
            comboBoxStepList.TextChanged += comboBoxStepList_TextChanged;
        }

        private void DataGridViewStep_DataBindingComplete(object sender, DataGridViewBindingCompleteEventArgs e)
        {
            ApplyTwoDecimalFormatting(dataGridViewStep);
        }

        private static void ApplyTwoDecimalFormatting(DataGridView grid)
        {
            if (grid == null)
                return;

            try
            {
                foreach (DataGridViewColumn c in grid.Columns)
                {
                    if (c == null)
                        continue;

                    var name = (c.Name ?? string.Empty);
                    var header = (c.HeaderText ?? string.Empty);
                    var combined = (name + "|" + header);

                    // Accuracy should always be 2 decimals.
                    if (combined.IndexOf("Accuracy", StringComparison.OrdinalIgnoreCase) >= 0)
                    {
                        c.DefaultCellStyle.Format = "0.00";
                        continue;
                    }

                    // Temp/Humidity columns shown to the user should be 2 decimals; count fields excluded.
                    if (combined.IndexOf("Count", StringComparison.OrdinalIgnoreCase) >= 0)
                        continue;

                    if (combined.IndexOf("Temp", StringComparison.OrdinalIgnoreCase) >= 0
                        || combined.IndexOf("Temperature", StringComparison.OrdinalIgnoreCase) >= 0
                        || combined.IndexOf("Hum", StringComparison.OrdinalIgnoreCase) >= 0
                        || combined.IndexOf("Humidity", StringComparison.OrdinalIgnoreCase) >= 0)
                    {
                        c.DefaultCellStyle.Format = "0.00";
                    }
                }
            }
            catch { }
        }

        private void comboBoxStepList_TextChanged(object sender, EventArgs e)
        {
            var name = (comboBoxStepList.Text ?? string.Empty).Trim();
            buttonSave.Enabled = !string.Equals(name, NewProcedureName, StringComparison.OrdinalIgnoreCase);
        }

        private void StepEditor_Load(object sender, EventArgs e)
        {
            try
            {
                Data.InitializeDatabase();

                comboBoxStepList.Items.Clear();
                comboBoxStepList.Items.Add(NewProcedureName);
                foreach (var n in Data.GetProcedureNames())
                    comboBoxStepList.Items.Add(n);

                if (string.IsNullOrWhiteSpace(comboBoxStepList.Text))
                    comboBoxStepList.Text = NewProcedureName;

                buttonSave.Text = "Save";
            }
            catch
            {
                // keep UI usable even if DB is missing/unavailable
                if (comboBoxStepList.Items.Count == 0)
                    comboBoxStepList.Items.Add(NewProcedureName);
            }
        }

        private void comboBoxStepList_SelectedIndexChanged(object sender, EventArgs e)
        {
            var name = (comboBoxStepList.Text ?? string.Empty).Trim();
            if (string.Equals(name, NewProcedureName, StringComparison.OrdinalIgnoreCase))
            {
                buttonSave.Text = "Save";
                buttonSave.Enabled = false;
                try
                {
                    richTextBoxDescription.Text = string.Empty;
                    dataGridViewStep.Rows.Clear();
                    _hasUnsavedChanges = false;
                }
                catch { }
                return;
            }

            buttonSave.Enabled = true;

            if (string.IsNullOrWhiteSpace(name))
                return;

            try
            {
                Data.InitializeDatabase();
                var rows = Data.GetProcedureRows(name);
                if (rows == null || rows.Count == 0)
                    return;

                dataGridViewStep.Rows.Clear();
                richTextBoxDescription.Text = rows[0].Description ?? string.Empty;

                foreach (var r in rows)
                {
                    int idx = dataGridViewStep.Rows.Add();
                    var gridRow = dataGridViewStep.Rows[idx];
                    gridRow.Cells["Step"].Value = r.Step ?? string.Empty;
                    gridRow.Cells["SetPointRH"].Value = r.HumiditySetpoint.HasValue ? r.HumiditySetpoint.Value.ToString(System.Globalization.CultureInfo.InvariantCulture) : string.Empty;
                    gridRow.Cells["SetPointTemp"].Value = r.TemperatureSetpointC.HasValue ? r.TemperatureSetpointC.Value.ToString(System.Globalization.CultureInfo.InvariantCulture) : string.Empty;
                    gridRow.Cells["SoakTime"].Value = r.SoakTime ?? string.Empty;
                    gridRow.Cells["Accuracy"].Value = r.Accuracy.HasValue ? r.Accuracy.Value.ToString(System.Globalization.CultureInfo.InvariantCulture) : string.Empty;
                    gridRow.Cells["Adjust"].Value = r.Adjustment.HasValue ? r.Adjustment.Value : false;

                    ApplySpecialRowState(idx);
                }

                ApplyAdvancedTempBlockState();

                _hasUnsavedChanges = false;
                buttonSave.Text = "Update";
            }
            catch (Exception ex)
            {
                MessageBox.Show(this, "Failed to load procedure: " + ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private int FindAdjustPointColumnIndex()
        {
            // Prefer designer name "ColumnAdjust" but also allow header text match.
            int idx = FindColumnIndexByName("ColumnAdjust");
            if (idx >= 0) return idx;
            idx = FindColumnIndexByName("Adjustment Point?");
            if (idx >= 0) return idx;

            for (int i = 0; i < dataGridViewStep.Columns.Count; i++)
            {
                var c = dataGridViewStep.Columns[i];
                string combined = ((c?.Name ?? "") + "|" + (c?.HeaderText ?? "")).ToLowerInvariant();
                if (combined.Contains("adjust") && combined.Contains("point"))
                    return i;
            }
            return -1;
        }

        private bool IsTemperatureStepRow(int rowIndex)
        {
            if (rowIndex < 0 || rowIndex >= dataGridViewStep.Rows.Count)
                return false;

            int stepCol = FindStepColumnIndex();
            if (stepCol < 0)
                return false;

            var v = dataGridViewStep.Rows[rowIndex].Cells[stepCol]?.Value;
            var s = (v?.ToString() ?? string.Empty).Trim();
            return string.Equals(s, "Temperature", StringComparison.OrdinalIgnoreCase);
        }


        private int FindStepColumnIndex()
        {
            // Prefer an explicit column name, but fall back to any column whose name/header contains "step".
            int idx = FindColumnIndexByName("Step");
            if (idx >= 0) return idx;

            for (int i = 0; i < dataGridViewStep.Columns.Count; i++)
            {
                var c = dataGridViewStep.Columns[i];
                string combined = ((c?.Name ?? "") + "|" + (c?.HeaderText ?? "")).ToLowerInvariant();
                if (combined.Contains("step"))
                    return i;
            }
            return -1;
        }

        private string GetStepText(int rowIndex)
        {
            if (rowIndex < 0 || rowIndex >= dataGridViewStep.Rows.Count)
                return string.Empty;

            int stepCol = FindStepColumnIndex();
            if (stepCol < 0)
                return string.Empty;

            var cellVal = dataGridViewStep.Rows[rowIndex].Cells[stepCol]?.Value;
            return (cellVal?.ToString() ?? string.Empty).Trim();
        }

        private bool IsSpecialStepText(string stepText)
        {
            return string.Equals(stepText, "Adjust", StringComparison.OrdinalIgnoreCase)
                || string.Equals(stepText, "AdvancedTempStart", StringComparison.OrdinalIgnoreCase)
                || string.Equals(stepText, "AdvancedTempEnd", StringComparison.OrdinalIgnoreCase)
                || string.Equals(stepText, "Factory", StringComparison.OrdinalIgnoreCase)
                || string.Equals(stepText, "As-FoundStart", StringComparison.OrdinalIgnoreCase)
                || string.Equals(stepText, "As-FoundEnd", StringComparison.OrdinalIgnoreCase)
                || string.Equals(stepText, "As-LeftStart", StringComparison.OrdinalIgnoreCase)
                || string.Equals(stepText, "As-LeftEnd", StringComparison.OrdinalIgnoreCase);
        }

        private bool IsSpecialStepRow(int rowIndex)
        {
            return IsSpecialStepText(GetStepText(rowIndex));
        }

        private void ApplySpecialRowState(int rowIndex)
        {
            if (rowIndex < 0 || rowIndex >= dataGridViewStep.Rows.Count)
                return;

            int stepCol = FindStepColumnIndex();
            if (stepCol < 0)
                return;

            bool isSpecialStep = IsSpecialStepRow(rowIndex);

            var row = dataGridViewStep.Rows[rowIndex];
            for (int c = 0; c < dataGridViewStep.Columns.Count; c++)
            {
                if (c == stepCol)
                    continue;

                var cell = row.Cells[c];
                if (cell == null)
                    continue;

                cell.ReadOnly = isSpecialStep;

                if (isSpecialStep)
                {
                    // Clear values and uncheck checkboxes.
                    if (cell is DataGridViewCheckBoxCell)
                        cell.Value = false;
                    else
                        cell.Value = null;
                }
            }

            try { dataGridViewStep.InvalidateRow(rowIndex); } catch { }
        }

        private void StepEditor_FormClosing(object sender, FormClosingEventArgs e)
        {
            // If there are no unsaved changes, just allow close
            if (!_hasUnsavedChanges)
                return;

            // Ask the user whether to proceed without saving
            bool proceed = UnsavedChangesWarning();
            if (!proceed)
            {
                // User cancelled -> keep the form open
                e.Cancel = true;
            }
            // If proceed is true, allow closing (no need to set e.Cancel)
        }

        private bool UnsavedChangesWarning()
        {
            var message = "There are unsaved changes. Do you want to proceed without saving?";
            var caption = "Unsaved Changes";
            var result = MessageBox.Show(this, message, caption, MessageBoxButtons.OKCancel, MessageBoxIcon.Warning);
            return result == DialogResult.OK;
        }

        // Event handlers to mark the form as having unsaved changes
        private void DataGridViewStep_Changed(object sender, EventArgs e)
        {
            _hasUnsavedChanges = true;

            // If this was a CellValueChanged event, check for pass/fail toggles and clear dependent fields
            if (e is DataGridViewCellEventArgs cellArgs)
            {
                int rowIndex = cellArgs.RowIndex;
                int colIndex = cellArgs.ColumnIndex;
                if (rowIndex < 0 || colIndex < 0)
                    return;

                var col = dataGridViewStep.Columns[colIndex];
                string colName = (col?.Name ?? col?.HeaderText ?? string.Empty).Trim();

                // When temp pass/fail is toggled and becomes unchecked, clear temperature accuracy
                if (string.Equals(colName, "temppassfail", StringComparison.OrdinalIgnoreCase))
                {
                    bool pass = GetCellBoolValue(rowIndex, colIndex);
                    if (!pass)
                    {
                        ClearTempFields(rowIndex);
                    }
                }

                // When hum pass/fail is toggled and becomes unchecked, clear humidity accuracy
                if (string.Equals(colName, "humppassfail", StringComparison.OrdinalIgnoreCase) ||
                    string.Equals(colName, "humpassfail", StringComparison.OrdinalIgnoreCase))
                {
                    bool pass = GetCellBoolValue(rowIndex, colIndex);
                    if (!pass)
                    {
                        ClearHumFields(rowIndex);
                    }
                }

                // If the Step column changes, enforce Adjust-row behavior.
                if (colIndex == FindStepColumnIndex())
                {
                    ApplySpecialRowState(rowIndex);

                    // Enforce AdvancedTemp block restrictions after step changes.
                    ApplyAdvancedTempBlockState();

                }
            }
        }

        private bool IsAdvancedTempMarker(string stepText)
        {
            return string.Equals(stepText, "AdvancedTempStart", StringComparison.OrdinalIgnoreCase)
                || string.Equals(stepText, "AdvancedTempEnd", StringComparison.OrdinalIgnoreCase);
        }

        private bool IsBetweenAdvancedTempMarkers(int rowIndex)
        {
            if (rowIndex < 0 || rowIndex >= dataGridViewStep.Rows.Count)
                return false;

            int startRow = -1;
            int endRow = -1;
            for (int i = 0; i < dataGridViewStep.Rows.Count; i++)
            {
                if (dataGridViewStep.Rows[i].IsNewRow)
                    continue;

                var stepText = GetStepText(i);
                if (string.Equals(stepText, "AdvancedTempStart", StringComparison.OrdinalIgnoreCase))
                    startRow = i;
                else if (string.Equals(stepText, "AdvancedTempEnd", StringComparison.OrdinalIgnoreCase))
                    endRow = i;
            }

            if (startRow < 0 || endRow < 0)
                return false;

            if (endRow <= startRow)
                return false;

            return rowIndex > startRow && rowIndex < endRow;
        }

        private void ApplyAdvancedTempBlockState()
        {
            int adjustCol = FindAdjustPointColumnIndex();
            if (adjustCol < 0)
                return;

            for (int r = 0; r < dataGridViewStep.Rows.Count; r++)
            {
                var row = dataGridViewStep.Rows[r];
                if (row == null || row.IsNewRow)
                    continue;

                var stepText = GetStepText(r);
                if (IsAdvancedTempMarker(stepText))
                    continue;

                bool inBlock = IsBetweenAdvancedTempMarkers(r);
                var cell = row.Cells[adjustCol];
                if (cell == null)
                    continue;

                if (inBlock)
                {
                    cell.ReadOnly = true;
                    if (cell is DataGridViewCheckBoxCell)
                        cell.Value = false;
                    else
                        cell.Value = null;
                }
                else
                {
                    // Only re-enable if it isn't already disabled by other row rules.
                    if (!IsSpecialStepRow(r))
                        cell.ReadOnly = false;
                }
            }

            try { dataGridViewStep.Invalidate(); } catch { }
        }

        private void DataGridViewStep_CellBeginEdit(object sender, DataGridViewCellCancelEventArgs e)
        {
            if (e.RowIndex < 0 || e.ColumnIndex < 0)
                return;

            int stepCol = FindStepColumnIndex();
            if (stepCol < 0)
                return;

            // If this row is a special step, block editing of all non-step cells.
            if (e.ColumnIndex != stepCol && IsSpecialStepRow(e.RowIndex))
            {
                e.Cancel = true;
            }

            // Disable adjustment checkbox between AdvancedTempStart and AdvancedTempEnd
            int adjustCol = FindAdjustPointColumnIndex();
            if (adjustCol >= 0 && e.ColumnIndex == adjustCol && IsBetweenAdvancedTempMarkers(e.RowIndex))
            {
                e.Cancel = true;
            }

        }

        private void DataGridViewStep_CellContentClick(object sender, DataGridViewCellEventArgs e)
        {
            // CheckBox cells can toggle on click even when BeginEdit is cancelled in some cases.
            if (e.RowIndex < 0 || e.ColumnIndex < 0)
                return;

        }

        private void DataGridViewStep_CellFormatting(object sender, DataGridViewCellFormattingEventArgs e)
        {
            if (e.RowIndex < 0 || e.ColumnIndex < 0)
                return;

            int stepCol = FindStepColumnIndex();
            if (stepCol < 0)
                return;

            if (e.ColumnIndex == stepCol)
                return;

            if (IsSpecialStepRow(e.RowIndex))
            {
                e.CellStyle.BackColor = SystemColors.Control;
                e.CellStyle.ForeColor = SystemColors.GrayText;
            }
            else
            {
                e.CellStyle.BackColor = dataGridViewStep.DefaultCellStyle.BackColor;
                e.CellStyle.ForeColor = dataGridViewStep.DefaultCellStyle.ForeColor;
            }

            int adjustCol = FindAdjustPointColumnIndex();
            if (adjustCol >= 0 && e.ColumnIndex == adjustCol && IsBetweenAdvancedTempMarkers(e.RowIndex))
            {
                e.CellStyle.BackColor = SystemColors.Control;
                e.CellStyle.ForeColor = SystemColors.GrayText;
            }

            // Force 2 decimals for temp/humidity/accuracy display even if the underlying cell is a string.
            try
            {
                var col = dataGridViewStep.Columns[e.ColumnIndex];
                var combined = ((col?.Name ?? string.Empty) + "|" + (col?.HeaderText ?? string.Empty));

                if (combined.IndexOf("Count", StringComparison.OrdinalIgnoreCase) < 0
                    && (combined.IndexOf("Accuracy", StringComparison.OrdinalIgnoreCase) >= 0
                        || combined.IndexOf("Temp", StringComparison.OrdinalIgnoreCase) >= 0
                        || combined.IndexOf("Temperature", StringComparison.OrdinalIgnoreCase) >= 0
                        || combined.IndexOf("Hum", StringComparison.OrdinalIgnoreCase) >= 0
                        || combined.IndexOf("Humidity", StringComparison.OrdinalIgnoreCase) >= 0))
                {
                    if (e.Value != null && e.Value != DBNull.Value)
                    {
                        if (double.TryParse(Convert.ToString(e.Value, System.Globalization.CultureInfo.InvariantCulture),
                            System.Globalization.NumberStyles.Float | System.Globalization.NumberStyles.AllowThousands,
                            System.Globalization.CultureInfo.InvariantCulture, out var d)
                            || double.TryParse(Convert.ToString(e.Value, System.Globalization.CultureInfo.CurrentCulture),
                            System.Globalization.NumberStyles.Float | System.Globalization.NumberStyles.AllowThousands,
                            System.Globalization.CultureInfo.CurrentCulture, out d))
                        {
                            e.Value = d.ToString("0.00", System.Globalization.CultureInfo.InvariantCulture);
                            e.FormattingApplied = true;
                        }
                    }
                }
            }
            catch { }

        }

        private void DataGridViewStep_CurrentCellDirtyStateChanged(object sender, EventArgs e)
        {
            // If the current cell is dirty, commit the edit so CellValueChanged fires
            if (dataGridViewStep.IsCurrentCellDirty)
            {
                dataGridViewStep.CommitEdit(DataGridViewDataErrorContexts.Commit);
            }
            _hasUnsavedChanges = true;
        }

        // Validate cell edits: prevent entering values into accuracy fields when pass/fail is unchecked
        private void DataGridViewStep_CellValidating(object sender, DataGridViewCellValidatingEventArgs e)
        {
            if (e.RowIndex < 0 || e.ColumnIndex < 0)
                return;

            var col = dataGridViewStep.Columns[e.ColumnIndex];
            string colName = (col?.Name ?? col?.HeaderText ?? string.Empty).Trim();
            string combined = ((col?.Name ?? "") + "|" + (col?.HeaderText ?? "")).ToLowerInvariant();

            // Temperature accuracy protection: any column that contains "accuracy" and "temp"/"temperature"
            bool isTempAccuracy = combined.Contains("accuracy") && (combined.Contains("temp") || combined.Contains("temperature"));

            // Humidity accuracy protection: any column that contains "accuracy" and "hum"/"humidity"
            bool isHumAccuracy = combined.Contains("accuracy") && (combined.Contains("hum") || combined.Contains("humidity"));

            if (isTempAccuracy)
            {
                int tempPassCol = FindColumnIndexByName("temppassfail");
                if (tempPassCol >= 0)
                {
                    bool pass = GetCellBoolValue(e.RowIndex, tempPassCol);
                    if (!pass)
                    {
                        // Prevent entry by clearing the attempted value
                        dataGridViewStep.Rows[e.RowIndex].Cells[e.ColumnIndex].Value = null;
                        // Do not cancel navigation; simply enforce empty value
                        e.Cancel = false;
                        _hasUnsavedChanges = true;
                    }
                }
            }

            if (isHumAccuracy)
            {
                int humPassCol = FindColumnIndexByName("humppassfail");
                if (humPassCol < 0)
                    humPassCol = FindColumnIndexByName("humpassfail"); // support alternate name

                if (humPassCol >= 0)
                {
                    bool pass = GetCellBoolValue(e.RowIndex, humPassCol);
                    if (!pass)
                    {
                        dataGridViewStep.Rows[e.RowIndex].Cells[e.ColumnIndex].Value = null;
                        e.Cancel = false;
                        _hasUnsavedChanges = true;
                    }
                }
            }
        }

        private void newListToolStripMenuItem_Click(object sender, EventArgs e)
        {
            // Menu action kept for compatibility with existing designer wiring.
            comboBoxStepList.Text = NewProcedureName;
        }
        private bool DataLossWarning()
        {
            {
            var message = "This will clear any unsaved changes. Proceed?";
            var caption = "Confirm";
            var result = MessageBox.Show(this, message, caption, MessageBoxButtons.OKCancel, MessageBoxIcon.Warning);

                if (result != DialogResult.OK)
                    return false;
                ClearData();
                return true;
            }
        }
        private void ClearData()
        {

            // If the grid is bound to a DataSource, try to clear the underlying data safely.
            if (dataGridViewStep.DataSource != null)
            {
                // If DataSource is a DataTable
                if (dataGridViewStep.DataSource is DataTable dt)
                {
                    dt.Clear();
                }
                else if (dataGridViewStep.DataSource is BindingSource bs)
                {
                    // If the BindingSource wraps a DataTable, clear it; otherwise detach the BindingSource.
                    if (bs.DataSource is DataTable bsTable)
                    {
                        bsTable.Clear();
                    }
                    else
                    {
                        bs.DataSource = null;
                        dataGridViewStep.DataSource = null;
                    }
                }
                else
                {
                    // Fallback: unbind the grid
                    dataGridViewStep.DataSource = null;
                }

                // Ensure any remaining rows are removed for safety
                if (dataGridViewStep.Rows.Count > 0 && dataGridViewStep.DataSource == null)
                    dataGridViewStep.Rows.Clear();
            }
            else
            {
                // Unbound grid: clear rows
                dataGridViewStep.Rows.Clear();
            }

            // Clearing data is a change that is not saved
            _hasUnsavedChanges = true;
        }

        private void saveToolStripMenuItem_Click(object sender, EventArgs e)
        {
            // Menu action kept for compatibility with existing designer wiring.
            // Persist using the main Save/Update button instead of Excel.
            if (buttonSave.Enabled)
                buttonSave.PerformClick();
        }

        private bool DataValidation()
        {

            /* Plan (detailed pseudocode):
             1. Change signature to return bool: true when validation passes (no errors), false when errors found.
             2. Keep existing validation logic intact.
             3. When errors are found:
                - Focus the first invalid cell if possible.
                - Show combined message box.
                - Return false.
             4. When no errors:
                - Clear lingering ErrorText values.
                - Return true.
             5. Ensure no other behavioral changes.
            */

            // Local helpers
            int FindColumnIndexContaining(params string[] tokens)
            {
                if (tokens == null || tokens.Length == 0)
                    return -1;

                for (int i = 0; i < dataGridViewStep.Columns.Count; i++)
                {
                    var c = dataGridViewStep.Columns[i];
                    string combined = ((c?.Name ?? "") + "|" + (c?.HeaderText ?? "")).ToLowerInvariant();
                    bool all = true;
                    foreach (var t in tokens)
                    {
                        if (string.IsNullOrWhiteSpace(t))
                            continue;
                        if (!combined.Contains(t.ToLowerInvariant().Trim()))
                        {
                            all = false;
                            break;
                        }
                    }
                    if (all)
                        return i;
                }
                return -1;
            }

            bool TryParseTwoDecimal(string raw, out double result)
            {
                result = 0;
                if (string.IsNullOrWhiteSpace(raw))
                    return false;

                string s = raw.Trim();
                // Allow comma as decimal separator by normalizing to dot
                s = s.Replace(',', '.');

                // Reject if there are multiple dots
                int dotCount = s.Count(ch => ch == '.');
                if (dotCount > 1)
                    return false;

                // Remove leading + sign
                if (s.StartsWith("+"))
                    s = s.Substring(1);

                // Use invariant culture for parsing after normalization
                if (!double.TryParse(s, System.Globalization.NumberStyles.Float, System.Globalization.CultureInfo.InvariantCulture, out result))
                    return false;

                // Check decimal places by inspecting the normalized string (avoid floating rounding issues)
                int idx = s.IndexOf('.');
                if (idx < 0)
                {
                    // integer -> 0 decimals -> allowed
                    return true;
                }

                string frac = s.Substring(idx + 1);
                // If frac contains exponent part (e.g. "1.23e3"), split at 'e' or 'E'
                int eidx = frac.IndexOfAny(new char[] { 'e', 'E' });
                if (eidx >= 0)
                    frac = frac.Substring(0, eidx);

                // Disallow more than 2 decimal digits
                if (frac.Length > 2)
                    return false;

                return true;
            }

            string FormatTwoDecimal(double value)
            {
                // Use current culture formatting to present to the user, but ensure two decimals
                return value.ToString("F2", System.Globalization.CultureInfo.CurrentCulture);
            }

            // Identify columns (best-effort)
            int colStep = FindColumnIndexContaining("step");
            int colTempSet = FindColumnIndexContaining("temp", "set");
            int colHumSet = FindColumnIndexContaining("hum", "set");
            int colEvalTemp = FindColumnIndexContaining("eval", "temp");
            if (colEvalTemp < 0) colEvalTemp = FindColumnIndexContaining("evaluate", "temp");
            int colEvalHum = FindColumnIndexContaining("eval", "hum");
            if (colEvalHum < 0) colEvalHum = FindColumnIndexContaining("evaluate", "hum");

            // Accuracy columns (new behaviour)
            int colTempAccuracy = -1;
            int colHumAccuracy = -1;
            for (int i = 0; i < dataGridViewStep.Columns.Count; i++)
            {
                var c = dataGridViewStep.Columns[i];
                string combined = ((c?.Name ?? "") + "|" + (c?.HeaderText ?? "")).ToLowerInvariant();
                if (combined.Contains("accuracy") && (combined.Contains("temp") || combined.Contains("temperature")))
                    colTempAccuracy = i;
                if (combined.Contains("accuracy") && (combined.Contains("hum") || combined.Contains("humidity")))
                    colHumAccuracy = i;
            }

            var errors = new List<string>();
            DataGridViewCell firstInvalidCell = null;
            int advancedTempStartCount = 0;
            int advancedTempEndCount = 0;
            DataGridViewCell firstAdvancedTempStartCell = null;

            for (int rowIndex = 0; rowIndex < dataGridViewStep.Rows.Count; rowIndex++)
            {
                var row = dataGridViewStep.Rows[rowIndex];
                if (row.IsNewRow)
                    continue;

                bool isSpecialStepRow = false;
                string stepText = string.Empty;
                try
                {
                    if (colStep >= 0)
                    {
                        var stepVal = row.Cells[colStep]?.Value;
                        stepText = (stepVal?.ToString() ?? string.Empty).Trim();
                        isSpecialStepRow = IsSpecialStepText(stepText);

                        if (string.Equals(stepText, "AdvancedTempStart", StringComparison.OrdinalIgnoreCase))
                        {
                            advancedTempStartCount++;
                            if (firstAdvancedTempStartCell == null)
                                firstAdvancedTempStartCell = row.Cells[colStep];
                        }

                        if (string.Equals(stepText, "AdvancedTempEnd", StringComparison.OrdinalIgnoreCase))
                            advancedTempEndCount++;
                    }
                }
                catch { isSpecialStepRow = false; }

                // Clear any previous error texts on this row's cells (we'll set if needed)
                foreach (DataGridViewCell c in row.Cells)
                    c.ErrorText = string.Empty;

                // 1) Step column selected
                if (colStep >= 0)
                {
                    var stepCell = row.Cells[colStep];
                    var val = stepCell?.Value;
                    if (val == null || string.IsNullOrWhiteSpace(val.ToString()))
                    {
                        string msg = $"Row {rowIndex + 1}: Step not selected.";
                        errors.Add(msg);
                        if (firstInvalidCell == null) firstInvalidCell = stepCell;
                        if (stepCell != null) stepCell.ErrorText = "Select a step";
                    }
                }

                // 2) Temperature setpoint must be valid double with up to 2 decimals; format to 2 decimals
                if (colTempSet >= 0)
                {
                    var cell = row.Cells[colTempSet];
                    var raw = cell?.Value?.ToString() ?? string.Empty;
                    if (string.IsNullOrWhiteSpace(raw))
                    {
                        if (!isSpecialStepRow)
                        {
                            string msg = $"Row {rowIndex + 1}: Temperature set point is empty or invalid.";
                            errors.Add(msg);
                            if (firstInvalidCell == null) firstInvalidCell = cell;
                            if (cell != null) cell.ErrorText = "Enter temperature set point";
                        }
                    }
                    else
                    {
                        if (!TryParseTwoDecimal(raw, out double parsed))
                        {
                            string msg = $"Row {rowIndex + 1}: Temperature set point must be a number with at most 2 decimals.";
                            errors.Add(msg);
                            if (firstInvalidCell == null) firstInvalidCell = cell;
                            if (cell != null) cell.ErrorText = "Invalid format (max 2 decimals)";
                        }
                        else
                        {
                            // Normalize/formatted display to 2 decimals
                            try
                            {
                                cell.Value = FormatTwoDecimal(parsed);
                            }
                            catch { /* ignore formatting failure */ }
                        }
                    }
                }

                // 3) Humidity setpoint must be valid double with up to 2 decimals; format to 2 decimals
                if (colHumSet >= 0)
                {
                    var cell = row.Cells[colHumSet];
                    var raw = cell?.Value?.ToString() ?? string.Empty;
                    if (string.IsNullOrWhiteSpace(raw))
                    {
                        if (!isSpecialStepRow)
                        {
                            string msg = $"Row {rowIndex + 1}: Humidity set point is empty or invalid.";
                            errors.Add(msg);
                            if (firstInvalidCell == null) firstInvalidCell = cell;
                            if (cell != null) cell.ErrorText = "Enter humidity set point";
                        }
                    }
                    else
                    {
                        if (!TryParseTwoDecimal(raw, out double parsed))
                        {
                            string msg = $"Row {rowIndex + 1}: Humidity set point must be a number with at most 2 decimals.";
                            errors.Add(msg);
                            if (firstInvalidCell == null) firstInvalidCell = cell;
                            if (cell != null) cell.ErrorText = "Invalid format (max 2 decimals)";
                        }
                        else
                        {
                            try
                            {
                                cell.Value = FormatTwoDecimal(parsed);
                            }
                            catch { /* ignore formatting failure */ }
                        }
                    }
                }

                // 4) Evaluate Temperature checkbox -> if checked validate temperature accuracy column, else it must be blank
                if (colEvalTemp >= 0)
                {
                    bool evalTemp = GetCellBoolValue(rowIndex, colEvalTemp);

                    if (evalTemp)
                    {
                        if (colTempAccuracy >= 0)
                        {
                            var cAcc = row.Cells[colTempAccuracy];
                            var raw = cAcc?.Value?.ToString() ?? string.Empty;
                            if (string.IsNullOrWhiteSpace(raw))
                            {
                                string msg = $"Row {rowIndex + 1}: Temperature accuracy is required when Evaluate Temperature is checked.";
                                errors.Add(msg);
                                if (firstInvalidCell == null) firstInvalidCell = cAcc;
                                if (cAcc != null) cAcc.ErrorText = "Required";
                            }
                            else if (!TryParseTwoDecimal(raw, out double pacc))
                            {
                                string msg = $"Row {rowIndex + 1}: Temperature accuracy must be a number with at most 2 decimals.";
                                errors.Add(msg);
                                if (firstInvalidCell == null) firstInvalidCell = cAcc;
                                if (cAcc != null) cAcc.ErrorText = "Invalid format";
                            }
                            else
                            {
                                try { cAcc.Value = FormatTwoDecimal(pacc); } catch { }
                            }
                        }
                        else
                        {
                            // If evaluation requires temperature accuracy but no such column exists, mark as error
                            string msg = $"Row {rowIndex + 1}: Evaluate Temperature is checked but no Temperature Accuracy column is present.";
                            errors.Add(msg);
                            if (firstInvalidCell == null) firstInvalidCell = dataGridViewStep.Rows[rowIndex].Cells[Math.Max(0, colEvalTemp)];
                        }
                    }
                    else
                    {
                        // If eval unchecked, accuracy should be blank (if column exists)
                        if (colTempAccuracy >= 0)
                        {
                            var cAcc = row.Cells[colTempAccuracy];
                            if (cAcc?.Value != null && !string.IsNullOrWhiteSpace(cAcc.Value.ToString()))
                            {
                                string msg = $"Row {rowIndex + 1}: Temperature accuracy must be blank when Evaluate Temperature is not checked.";
                                errors.Add(msg);
                                if (firstInvalidCell == null) firstInvalidCell = cAcc;
                                if (cAcc != null) cAcc.ErrorText = "Must be blank";
                            }
                        }
                    }
                }

                // 5) Evaluate Humidity checkbox -> if checked validate humidity accuracy column, else it must be blank
                if (colEvalHum >= 0)
                {
                    bool evalHum = GetCellBoolValue(rowIndex, colEvalHum);

                    if (evalHum)
                    {
                        if (colHumAccuracy >= 0)
                        {
                            var cAcc = row.Cells[colHumAccuracy];
                            var raw = cAcc?.Value?.ToString() ?? string.Empty;
                            if (string.IsNullOrWhiteSpace(raw))
                            {
                                string msg = $"Row {rowIndex + 1}: Humidity accuracy is required when Evaluate Humidity is checked.";
                                errors.Add(msg);
                                if (firstInvalidCell == null) firstInvalidCell = cAcc;
                                if (cAcc != null) cAcc.ErrorText = "Required";
                            }
                            else if (!TryParseTwoDecimal(raw, out double pacc))
                            {
                                string msg = $"Row {rowIndex + 1}: Humidity accuracy must be a number with at most 2 decimals.";
                                errors.Add(msg);
                                if (firstInvalidCell == null) firstInvalidCell = cAcc;
                                if (cAcc != null) cAcc.ErrorText = "Invalid format";
                            }
                            else
                            {
                                try { cAcc.Value = FormatTwoDecimal(pacc); } catch { }
                            }
                        }
                        else
                        {
                            string msg = $"Row {rowIndex + 1}: Evaluate Humidity is checked but no Humidity Accuracy column is present.";
                            errors.Add(msg);
                            if (firstInvalidCell == null) firstInvalidCell = dataGridViewStep.Rows[rowIndex].Cells[Math.Max(0, colEvalHum)];
                        }
                    }
                    else
                    {
                        if (colHumAccuracy >= 0)
                        {
                            var cAcc = row.Cells[colHumAccuracy];
                            if (cAcc?.Value != null && !string.IsNullOrWhiteSpace(cAcc.Value.ToString()))
                            {
                                string msg = $"Row {rowIndex + 1}: Humidity accuracy must be blank when Evaluate Humidity is not checked.";
                                errors.Add(msg);
                                if (firstInvalidCell == null) firstInvalidCell = cAcc;
                                if (cAcc != null) cAcc.ErrorText = "Must be blank";
                            }
                        }
                    }
                }
            } // end rows loop

            if (advancedTempStartCount > 1)
            {
                errors.Add("Only one AdvancedTempStart step is allowed.");
                if (firstInvalidCell == null)
                    firstInvalidCell = firstAdvancedTempStartCell;
                if (firstAdvancedTempStartCell != null)
                    firstAdvancedTempStartCell.ErrorText = "Only one AdvancedTempStart is allowed";
            }

            if (advancedTempStartCount > 0 && advancedTempEndCount == 0)
            {
                errors.Add("Every AdvancedTempStart step must have a matching AdvancedTempEnd step.");
                if (firstInvalidCell == null)
                    firstInvalidCell = firstAdvancedTempStartCell;
                if (firstAdvancedTempStartCell != null)
                    firstAdvancedTempStartCell.ErrorText = "AdvancedTempEnd is required";
            }

            if (errors.Count > 0)
            {
                try
                {
                    // Focus first invalid cell if available
                    if (firstInvalidCell != null)
                    {
                        dataGridViewStep.CurrentCell = firstInvalidCell;
                        dataGridViewStep.FirstDisplayedScrollingRowIndex = Math.Max(0, firstInvalidCell.RowIndex - 2);
                    }
                }
                catch { /* ignore focus errors */ }

                string msg = "Validation failed:\n" + string.Join("\n", errors.Distinct());
                MessageBox.Show(this, msg, "Validation Errors", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return false;
            }
            else
            {
                // Clear any lingering error texts
                foreach (DataGridViewRow row in dataGridViewStep.Rows)
                {
                    foreach (DataGridViewCell c in row.Cells)
                        c.ErrorText = string.Empty;
                }
                return true;
            }
        }

        private void loadListToolStripMenuItem_Click(object sender, EventArgs e)
        {
            // Menu action kept for compatibility with existing designer wiring.
            // Loading from DB is done by selecting a procedure from the dropdown.
            comboBoxStepList.DroppedDown = true;
        }

        private bool GridHasData()
        {
            // Check DataSource scenarios first for an accurate count
            if (dataGridViewStep.DataSource is DataTable dt)
            {
                return dt.Rows.Count > 0;
            }

            if (dataGridViewStep.DataSource is BindingSource bs)
            {
                // If BindingSource wraps a DataTable, use its row count
                if (bs.DataSource is DataTable bsDt)
                    return bsDt.Rows.Count > 0;

                // BindingSource exposes Count; use it if available
                try
                {
                    if (bs.Count > 0)
                        return true;
                }
                catch
                {
                    // Swallow and fallback to row inspection
                }
            }

            // Fallback for unbound or other binding types:
            // Inspect rows ignoring the NewRow placeholder. Consider a row with any non-empty cell as data.
            foreach (DataGridViewRow row in dataGridViewStep.Rows)
            {
                if (row.IsNewRow)
                    continue;

                foreach (DataGridViewCell cell in row.Cells)
                {
                    var v = cell?.Value;
                    if (v != null && !string.IsNullOrWhiteSpace(v.ToString()))
                        return true;
                }
            }

            return false;
        }

        // ----------------------------
        // Helper methods for new rules
        // ----------------------------
        private int FindColumnIndexByName(string name)
        {
            if (string.IsNullOrWhiteSpace(name))
                return -1;

            for (int i = 0; i < dataGridViewStep.Columns.Count; i++)
            {
                var c = dataGridViewStep.Columns[i];
                string colName = (c?.Name ?? c?.HeaderText ?? string.Empty).Trim();
                if (string.Equals(colName, name.Trim(), StringComparison.OrdinalIgnoreCase))
                    return i;
            }
            return -1;
        }

        private int FindTemperatureAccuracyColumnIndex()
        {
            for (int i = 0; i < dataGridViewStep.Columns.Count; i++)
            {
                var c = dataGridViewStep.Columns[i];
                string combined = ((c?.Name ?? "") + "|" + (c?.HeaderText ?? "")).ToLowerInvariant();
                if (combined.Contains("accuracy") && (combined.Contains("temp") || combined.Contains("temperature")))
                    return i;
            }
            return -1;
        }

        private int FindHumidityAccuracyColumnIndex()
        {
            for (int i = 0; i < dataGridViewStep.Columns.Count; i++)
            {
                var c = dataGridViewStep.Columns[i];
                string combined = ((c?.Name ?? "") + "|" + (c?.HeaderText ?? "")).ToLowerInvariant();
                if (combined.Contains("accuracy") && (combined.Contains("hum") || combined.Contains("humidity")))
                    return i;
            }
            return -1;
        }

        private bool GetCellBoolValue(int rowIndex, int colIndex)
        {
            try
            {
                var r = dataGridViewStep.Rows[rowIndex];
                var cell = r.Cells[colIndex];
                if (cell == null)
                    return false;

                var val = cell.Value;
                if (val == null)
                    return false;

                if (val is bool b)
                    return b;

                // Sometimes CheckBox column can be boolean-like strings or ints
                string s = val.ToString();
                if (bool.TryParse(s, out bool parsedBool))
                    return parsedBool;
                if (int.TryParse(s, out int intVal))
                    return intVal != 0;

                return false;
            }
            catch
            {
                return false;
            }
        }

        private void ClearTempFields(int rowIndex)
        {
            int accIdx = FindTemperatureAccuracyColumnIndex();

            if (accIdx >= 0 && rowIndex >= 0 && rowIndex < dataGridViewStep.Rows.Count)
                dataGridViewStep.Rows[rowIndex].Cells[accIdx].Value = null;

            _hasUnsavedChanges = true;
        }

        private void ClearHumFields(int rowIndex)
        {
            int accIdx = FindHumidityAccuracyColumnIndex();

            if (accIdx >= 0 && rowIndex >= 0 && rowIndex < dataGridViewStep.Rows.Count)
                dataGridViewStep.Rows[rowIndex].Cells[accIdx].Value = null;

            _hasUnsavedChanges = true;
        }

        // Build List<StepClass> from the grid. Tries to be robust to column naming.
        private List<StepClass> BuildStepListFromGrid()
        {
            var result = new List<StepClass>();

            if (dataGridViewStep == null || dataGridViewStep.Columns.Count == 0)
                return result;

            // Helper to find column by tokens (name or header contains all tokens)
            int FindColumnIndexContaining(params string[] tokens)
            {
                if (tokens == null || tokens.Length == 0)
                    return -1;

                for (int i = 0; i < dataGridViewStep.Columns.Count; i++)
                {
                    var c = dataGridViewStep.Columns[i];
                    string combined = ((c?.Name ?? "") + "|" + (c?.HeaderText ?? "")).ToLowerInvariant();
                    bool all = true;
                    foreach (var t in tokens)
                    {
                        if (string.IsNullOrWhiteSpace(t))
                            continue;
                        if (!combined.Contains(t.ToLowerInvariant().Trim()))
                        {
                            all = false;
                            break;
                        }
                    }
                    if (all)
                        return i;
                }
                return -1;
            }

            // Columns: Step, Humidity Set Point, Temperature Set Point, Soak Time, Accuracy Specification, Adjustment Point
            int colStep = FindColumnIndexContaining(nameof(StepClass.Step));
            if (colStep < 0) colStep = FindColumnIndexContaining("step");

            int colSetPointRH = FindColumnIndexContaining(nameof(StepClass.SetPointRH));
            if (colSetPointRH < 0) colSetPointRH = FindColumnIndexContaining("humidity", "set");
            if (colSetPointRH < 0) colSetPointRH = FindColumnIndexContaining("hum", "set");
            if (colSetPointRH < 0) colSetPointRH = FindColumnIndexContaining("rh", "set");

            int colSetPointTemp = FindColumnIndexContaining(nameof(StepClass.SetPointTemp));
            if (colSetPointTemp < 0) colSetPointTemp = FindColumnIndexContaining("temperature", "set");
            if (colSetPointTemp < 0) colSetPointTemp = FindColumnIndexContaining("temp", "set");

            int colSoakTime = FindColumnIndexContaining(nameof(StepClass.SoakTime));
            if (colSoakTime < 0) colSoakTime = FindColumnIndexContaining("soak", "time");

            int colAccuracy = FindColumnIndexContaining(nameof(StepClass.Accuracy));
            if (colAccuracy < 0) colAccuracy = FindColumnIndexContaining("accuracy", "spec");
            if (colAccuracy < 0) colAccuracy = FindColumnIndexContaining("accuracy");

            int colAdjust = FindColumnIndexContaining(nameof(StepClass.Adjust));
            if (colAdjust < 0) colAdjust = FindColumnIndexContaining("adjust", "point");

            string GetCellText(DataGridViewRow row, int colIndex)
            {
                if (colIndex < 0 || colIndex >= dataGridViewStep.Columns.Count)
                    return string.Empty;
                var cell = row.Cells[colIndex];
                if (cell?.Value == null)
                    return string.Empty;
                return cell.Value.ToString().Trim();
            }

            double ParseDoubleOrNaN(string s)
            {
                if (string.IsNullOrWhiteSpace(s))
                    return double.NaN;

                string t = s.Trim().Replace(',', '.');
                if (double.TryParse(t, System.Globalization.NumberStyles.Float, System.Globalization.CultureInfo.InvariantCulture, out double v))
                    return v;
                return double.NaN;
            }

            foreach (DataGridViewRow row in dataGridViewStep.Rows)
            {
                if (row == null || row.IsNewRow)
                    continue;

                var step = new StepClass
                {
                    Step = (colStep >= 0) ? GetCellText(row, colStep) : string.Empty,
                    SetPointRH = (colSetPointRH >= 0) ? ParseDoubleOrNaN(GetCellText(row, colSetPointRH)) : double.NaN,
                    SetPointTemp = (colSetPointTemp >= 0) ? ParseDoubleOrNaN(GetCellText(row, colSetPointTemp)) : double.NaN,
                    SoakTime = (colSoakTime >= 0) ? GetCellText(row, colSoakTime) : string.Empty,
                    Accuracy = (colAccuracy >= 0) ? ParseDoubleOrNaN(GetCellText(row, colAccuracy)) : double.NaN,
                  Adjust = (colAdjust >= 0) ? GetCellBoolValue(row.Index, colAdjust) : false
                };

                result.Add(step);
            }

            return result;
        }

        private void buttonSetup_Click(object sender, EventArgs e)
        {
            bool isValid = DataValidation();

            if (!isValid)
            {
                // Validation failed; do not proceed with calibration setup
                return;
            }
            if (!GridHasData())
            {
                MessageBox.Show(this, "No step file is loaded", "Validation", MessageBoxButtons.OK, MessageBoxIcon.Information);
                return;
            }
            // Build list of StepClass objects from the grid and pass to CalibrationSetupFrm
            var steps = BuildStepListFromGrid();
            var calForm = new CalibrationSetupFrm(steps);
            calForm.Show(this);
        }

        private void buttonSave_Click(object sender, EventArgs e)
        {
            if (buttonSave.Text == "Save")
            {

                // validate data
                if (!GridHasData())
                {
                    MessageBox.Show(this, "No steps to save.", "Save", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    return;
                }

                var name = (comboBoxStepList.Text ?? string.Empty).Trim();
                if (string.IsNullOrWhiteSpace(name))
                {
                    MessageBox.Show(this, "Enter a procedure name.", "Save", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    comboBoxStepList.Focus();
                    return;
                }

                if (string.Equals(name, NewProcedureName, StringComparison.OrdinalIgnoreCase))
                {
                    MessageBox.Show(this, "'" + NewProcedureName + "' is reserved. Enter a different procedure name.", "Save", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    comboBoxStepList.Focus();
                    return;
                }

                var steps = BuildStepListFromGrid();
                if (steps.Count == 0)
                {
                    MessageBox.Show(this, "No steps to save.", "Save", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    return;
                }

                try
                {
                    Data.InitializeDatabase();
                    Data.SaveProcedure(name, richTextBoxDescription.Text, steps);

                    comboBoxStepList.Items.Clear();
                    comboBoxStepList.Items.Add(NewProcedureName);
                    foreach (var n in Data.GetProcedureNames())
                        comboBoxStepList.Items.Add(n);
                    comboBoxStepList.Text = name;

                    _hasUnsavedChanges = false;
                    buttonSave.Text = "Update";
                }
                catch (Exception ex)
                {
                    MessageBox.Show(this, "Failed to save procedure: " + ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }
            if (buttonSave.Text == "Update")
            {
                // validate data
                if (!GridHasData())
                {
                    MessageBox.Show(this, "No steps to update.", "Update", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    return;
                }

                var name = (comboBoxStepList.Text ?? string.Empty).Trim();
                if (string.IsNullOrWhiteSpace(name))
                {
                    MessageBox.Show(this, "Select a procedure to update.", "Update", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    return;
                }

                if (string.Equals(name, NewProcedureName, StringComparison.OrdinalIgnoreCase))
                {
                    MessageBox.Show(this, "Select a saved procedure name to update.", "Update", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    return;
                }

                var steps = BuildStepListFromGrid();
                if (steps.Count == 0)
                {
                    MessageBox.Show(this, "No steps to update.", "Update", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    return;
                }

                try
                {
                    Data.InitializeDatabase();
                    Data.SaveProcedure(name, richTextBoxDescription.Text, steps);
                    _hasUnsavedChanges = false;

                    // keep in Update mode
                    if (!comboBoxStepList.Items.Contains(name))
                        comboBoxStepList.Items.Add(name);
                }
                catch (Exception ex)
                {
                    MessageBox.Show(this, "Failed to update procedure: " + ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }
        }

        private void StepEditor_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.Shift && e.KeyCode == Keys.Delete)
            {
                e.Handled = true;
                e.SuppressKeyPress = true;

                var name = (comboBoxStepList.Text ?? string.Empty).Trim();
                if (string.IsNullOrWhiteSpace(name) || string.Equals(name, NewProcedureName, StringComparison.OrdinalIgnoreCase))
                    return;

                var result = MessageBox.Show(this, "Delete procedure '" + name + "'?", "Delete", MessageBoxButtons.OKCancel, MessageBoxIcon.Warning);
                if (result != DialogResult.OK)
                    return;

                try
                {
                    Data.InitializeDatabase();
                    Data.DeleteProcedure(name);

                    comboBoxStepList.Items.Clear();
                    comboBoxStepList.Items.Add(NewProcedureName);
                    foreach (var n in Data.GetProcedureNames())
                        comboBoxStepList.Items.Add(n);

                    comboBoxStepList.Text = NewProcedureName;
                    richTextBoxDescription.Text = string.Empty;
                    dataGridViewStep.Rows.Clear();
                    _hasUnsavedChanges = false;
                    buttonSave.Text = "Save";
                    buttonSave.Enabled = false;
                }
                catch (Exception ex)
                {
                    MessageBox.Show(this, "Failed to delete procedure: " + ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }
        }
    }
}
